#code to calculate mean target achievement

`%notin%` <- Negate(`%in%`)

#load perc_protected data
###########################
#area calcs for ecorast_now/2C/4C_mapped.tif
perc_comparison_master<-read.csv("Tables/PA_perc_comparison_master.csv")
#area calcs generated by masking 2C/4C no analog regions in the ecorast_now_mapped
perc_2C_mask<-read.csv("Tables/area_now_2C_mask.csv")  
perc_4C_mask<-read.csv("Tables/area_now_4C_mask.csv")

#calcMTAforBiome or any vector of percents
mtaVec<-function(percVec)
{df<-percVec/0.3
df[df>1]<-1
return(mean(df))}

#calc MTA for an individual ecoregion
mtaEco<-function(perc)
{df<-perc/0.3
df[df>1]<-1
return(df)}

#############################################################################
#here we create subset table to analyze different factors influence on changing MTA
#1. basic MTA calcs - use perc_comparison with tot_area==0 excluded
base<-subset(perc_comparison_master, tot_area_current!=0)
rm0_2C<-subset(perc_comparison_master, tot_area_2C!=0)
rm0_4C<-subset(perc_comparison_master, tot_area_4C!=0)
#2. with No Analog regions in 2C/4C masked in current area totals & tot_area==0 excluded
now_2C_mask<-subset(perc_2C_mask, tot_area_current!=0)
now_4C_mask<-subset(perc_4C_mask, tot_area_current!=0)
#3. without No Analog masking & tot_area==0 included as perc=0 (not in current ecoregions)
#use base
#4. with No Analog masking & tot_area==0 included as perc=0



# Run the mta function for representation target 0.3 (30% protection of each ecoregion)		          

#generate df with MTA per ecoregion for all scenarios
mta_by_eco_now.df<-data.frame("ECO_ID"=base$ECO_ID, 
                              "mta_now"=mtaEco(base$PA_perc_current))
mta_by_eco_2C.df<-data.frame("ECO_ID"=rm0_2C$ECO_ID, 
                             "mta_2C"=mtaEco(rm0_2C$PA_perc_2C))
mta_by_eco_4C.df<-data.frame("ECO_ID"=rm0_4C$ECO_ID, 
                             "mta_4C"=mtaEco(rm0_4C$PA_perc_4C))
mta_by_eco_2C0.df<-data.frame("ECO_ID"=base$ECO_ID, 
                             "mta_2C_incl0"=mtaEco(base$PA_perc_2C))
mta_by_eco_4C0.df<-data.frame("ECO_ID"=base$ECO_ID, 
                             "mta_4C_incl0"=mtaEco(base$PA_perc_4C))
mta_eco_2C_mask.df<-data.frame("ECO_ID"=now_2C_mask$ECO_ID, "mta_now_2C_mask"=mtaEco(now_2C_mask$PA_perc_current))
mta_eco_4C_mask.df<-data.frame("ECO_ID"=now_4C_mask$ECO_ID, "mta_now_4C_mask"=mtaEco(now_4C_mask$PA_perc_current))

mta_by_eco.df<-merge(mta_by_eco_now.df, mta_by_eco_2C.df, by="ECO_ID", all=T) %>% merge(., mta_by_eco_4C.df, by="ECO_ID", all=T) %>% 
  merge(., mta_eco_2C_mask.df, by="ECO_ID", all=T) %>%merge(., mta_eco_4C_mask.df, by="ECO_ID", all=T) %>%
  merge(., mta_by_eco_2C0.df, by="ECO_ID", all=T) %>%merge(., mta_by_eco_4C0.df, by="ECO_ID", all=T)%>%merge(., LUT_plus, by="ECO_ID")
mta_by_eco.df$mta_2C_incl0_mask<-mta_by_eco.df$mta_2C_incl0
mta_by_eco.df$mta_2C_incl0_mask
write.csv(mta_by_eco.df, "Tables/mta_by_eco_plus.csv", row.names = F)


############################
## MTA by biome #########
#############################
#generate vector of MTAs for each biome
calc_mtaByBiome<-function(inputData, column)
{
  val<-vector()
  for (i in c(1:8, 10:13)){
    sub<-column[inputData$BIOME_ID==i]
    if (length(sub)==0)
    {val<- c(val, NA)}
    else
    {val<- c(val, mtaVec(sub))}
  }
  return(val)
}

#write csv containing MTA per biome for all scenarios
biomeMTA_plus<-data.frame(BIOME_NAME=LUT_biome$BIOME_NAME[c(1:8, 10:13)],
                          mta_now=calc_mtaByBiome(base, base$PA_perc_current), 
                          mta_now_2C_mask=calc_mtaByBiome(now_2C_mask, now_2C_mask$PA_perc_current), 
                          mta_2C_rm0=calc_mtaByBiome(rm0_2C, rm0_2C$PA_perc_2C), 
                          mta_2C_incl0=calc_mtaByBiome(base, base$PA_perc_2C), 
                          mta_now_4C_mask=calc_mtaByBiome(now_4C_mask, now_4C_mask$PA_perc_current), 
                          mta_4C_rm0=calc_mtaByBiome(rm0_4C, rm0_4C$PA_perc_4C), 
                          mta_4C_incl0=calc_mtaByBiome(base, base$PA_perc_4C))
write.csv(biomeMTA_plus, "Tables/biomeMTA_factorCorr.csv", row.names=F)


#doing WMW analysis between biome MTA changes
temp<-data.frame("perc"=base$PA_perc_current, "BIOME_ID"=base$BIOME_ID, "BIOME_NAME"=base$BIOME_NAME, "id"=rep(0, length(base$PA_perc_current)))
temp2<-data.frame("perc"=base$PA_perc_2C, "BIOME_ID"=base$BIOME_ID, "BIOME_NAME"=base$BIOME_NAME, "id"=rep(1, length(base$PA_perc_current)))
mask_2C<-rbind(temp, temp2)
temp<-data.frame("perc"=base$PA_perc_current, "BIOME_ID"=base$BIOME_ID, "BIOME_NAME"=base$BIOME_NAME, "id"=rep(0, length(base$PA_perc_current)))
temp2<-data.frame("perc"=base$PA_perc_4C, "BIOME_ID"=base$BIOME_ID, "BIOME_NAME"=base$BIOME_NAME, "id"=rep(1, length(base$PA_perc_current)))
mask_4C<-rbind(temp, temp2)

out<-data.frame("BIOME_NAME"=LUT_biome$BIOME_NAME[c(1:8, 10:13)], "now-2C_incl0_WMW_p"=mta_WMW(mask_2C), "now-4C_incl0_WMW_p"=mta_WMW(mask_4C))
write.csv(out, "Tables/WMW_biomeMTA.csv", row.names=F)

mta_WMW<-function(inData)
{
  vec<-vector()
  for (i in c(1:8, 10:13))
  {
    print(i)
    df<-subset(inData, BIOME_ID==i)
    vec<-rbind(vec, wilcox.test(perc~id, data=df)[[3]])}
  return(vec)
}



t<-mta_biomeBootstrap(mta_by_eco.df, mta_by_eco.df$mta_now)

globalMTA_plus<-data.frame(mta_now=mtaVec(base$PA_perc_current), 
                          mta_now_2C_mask=mtaVec(now_2C_mask$PA_perc_current), 
                          mta_2C_rm0=mtaVec(rm0_2C$PA_perc_2C), 
                          mta_2C_incl0=mtaVec(base$PA_perc_2C), 
                          mta_now_4C_mask=mtaVec(now_4C_mask$PA_perc_current), 
                          mta_4C_rm0=mtaVec(rm0_4C$PA_perc_4C), 
                          mta_4C_incl0=mtaVec(base$PA_perc_4C))
write.csv(globalMTA_plus, "Tables/MTA_factorCorr.csv", row.names=F)

data<-data[data$tot_area_current!=0, ]
data_lost_2C<-data[data$tot_area_2C==0, ]%>%subset(., select=c('econame', "tot_area_current", "PA_area_current", "BIOME_ID"))
colnames(data_lost_2C)<-c('feature', 'ai', 'pi', "BIOME_ID")
data_lost_4C<-data[data$tot_area_4C==0, ]%>%subset(., select=c('econame', "tot_area_current", "PA_area_current", "BIOME_ID"))
colnames(data_lost_4C)<-c('feature', 'ai', 'pi', "BIOME_ID")
#write CSV containing MTA of ecoregions lost to 2C/4C per biome
lostEcosMTAbyBiome<-data.frame(BIOME_NAME=as.character(unique(data_clean$BIOME_NAME)),
                                              lostEcosMTA_2C=calc_mtaByBiome(data_lost_2C),
                                        lostEcosMTA_4C=calc_mtaByBiome(data_lost_4C))
write.csv(lostEcosMTAbyBiome, "Tables/lostEcosMTAbyBiome.csv", row.names=F)                                             
